#cloud-config
hostname: ${HOSTNAME}
fqdn: ${HOSTNAME}.${SEARCH_DOMAIN}

manage_etc_hosts: false
package_upgrade: true
chpasswd:
  expire: True
ssh_pwauth: False
packages:
  - qemu-guest-agent
  - vim
runcmd:
  - systemctl start qemu-guest-agent
  - netplan apply
  - chown -R ${CI_USER}:${CI_USER} /home/${CI_USER}
users:
  - name: ${CI_USER}
    plain_text_passwd: ${CI_PASSWORD}
    groups: [adm,sudo]
    lock-passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    

# Documentation on data sources configuration options
datasource:
  NoCloud:
    seedfrom: https://raw.githubusercontent.com/Kipjr/cloud-init_ubuntu/master/
    fs_label: cidata
    user-data: |
    meta-data:
      instance-id: i-87018aed
      local-hostname: myhost.internal

# Keys such as autoinstall, preruncmd, and postruncmd are not used by cloud-init to configure anything.
autoinstall:
  version: 1
  refresh-installer:
    update: no
    channel: edge 
  early-commands: 
    - datetime="$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep 'Date:' | cut -d' ' -f5-8)Z" && /usr/bin/date -s "$datetime";
  apt:
    geoip: true
    preserve_sources_list: false
    primary:
      - arches:
          - amd64
        uri: 'http://archive.ubuntu.com/ubuntu'
      - arches:
          - default
        uri: 'http://ports.ubuntu.com/ubuntu-ports'
  identity: 
    hostname: ubuntu
    username: ubuntu
  user-data:
    disable_root: true
  keyboard: 
    layout: us
    toggle: null
    variant: intl
  locale: en_US.UTF-8
  ssh:
    allow-pw: false
    authorized-keys: []      
    install-server: false
  packages:
    - ca-certificates
  late-commands:
    - echo 1
  updates: security
  storage:
    version: 1
    config: 
      - id: disk0
        type: disk
        ptable: gpt
        match:
          size: largest
        wipe: superblock-recursive
        preserve: false
        name: ''
        grub_device: false
      - id: partition-0
        type: partition
        device: disk0
        size: 1G
        wipe: superblock-recursive
        flag: boot
        number: 1
        preserve: false
        grub_device: true
      - id: format-0
        type: format
        fstype: fat32
        volume: partition-0
        preserve: false
      - id: partition-1
        type: partition
        device: disk0
        size: 1G
        wipe: superblock-recursive
        flag: ''
        number: 2
        preserve: false
        grub_device: false
      - id: format-1
        type: format
        fstype: ext4
        volume: partition-1
        preserve: false
      - id: partition-2
        type: partition
        device: disk0
        size: -1
        wipe: superblock-recursive
        flag: ''
        number: 3
        preserve: false
        grub_device: false
      - id: format-2
        type: format
        fstype: ext4
        volume: partition-2
        preserve: false
      - id: mount-2
        type: mount
        device: format-2
        path: /
      - id: mount-1
        type: mount
        device: format-1
        path: /boot
      - id: mount-0
        type: mount
        device: format-0
        path: /boot/efi
  system_upgrade:
    enabled: True
  #error-commands:
