#cloud-config
hostname: ${CI_HOSTNAME}
fqdn: ${CI_HOSTNAME}.${CI_SEARCH_DOMAIN}
manage_etc_hosts: true

users:
  - name: ${CI_USER}
    plain_text_passwd: ${CI_PASSWORD}
    groups: [adm,sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ${CI_SSH_AUTH_KEY}
chpasswd:
  expire: true
ssh_pwauth: false

package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - software-properties-common
  - git
runcmd:
  - wget -O /tmp/script.sh https://raw.githubusercontent.com/Kipjr/cloud-init_ubuntu/master/standalone_ansible_playbook.sh && chmod +x /tmp/script.sh && sudo -u ${CI_USER} /tmp/script.sh
#ansible:
#  package_name: ansible
#  install_method: pip
#  galaxy:
#    actions:
#      - [ "collection", "install", "community.general" ]
#      - [ "collection", "install", "community.docker" ]
#  pull:
#    url: ${CI_GITHUB_ANSIBLE_PLAYBOOK}
#    playbook_name: site.yml
#    clean: true
#    full: true
