---
- name: Install roles and collections
  community.general.ansible_galaxy_install:
    type: both
    requirements_file: ./collections/requirements.yml
  
- name: Packages
  ansible.builtin.import_tasks: packages/main.yml

- name: Docker
  ansible.builtin.import_tasks: docker/main.yml

- name: Configuration
  ansible.builtin.import_tasks: configuration/main.yml

- name: Security
  ansible.builtin.import_tasks: security/main.yml
