---

- name: Download the Microsoft repository key file
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/config/ubuntu/{{ ansible_lsb.release }}/packages-microsoft-prod.deb"
    dest: "/tmp/packages-microsoft-prod.deb"
    mode: "0644"

- name: Register the Microsoft repository key
  become: true
  ansible.builtin.apt:
    deb: "/tmp/packages-microsoft-prod.deb"

- name: Remove the Microsoft repository key file
  ansible.builtin.file:
    path: "/tmp/packages-microsoft-prod.deb"
    state: absent

- name: Add Microsoft APT repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main"
    state: present

- name: Download Webmin Repo Setup
  when:
    - ubtu22_pkg_webmin
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
    dest: /tmp/setup-repos.sh
    mode: '0740'

- name: Configure Webmin Repo
  when:
    - ubtu22_pkg_webmin
  become: true
  args:
    creates: /etc/apt/sources.list.d/webmin.list
  ansible.builtin.shell: |
    sh /tmp/setup-repos.sh -f

- name: Ensure all packages are up to date
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name:
      - ufw
      - ethtool
      - htop
      - screen
      - nano
      - net-tools
      - dnsutils
      - openssl
      - build-essential
      - p7zip-full
      - curl
      - gnupg
      - apt-transport-https
      - ca-certificates
      - libssl-dev
      - software-properties-common
      - openssh-server
      - uidmap
      - dbus-user-session
      - unattended-upgrades
      - pkg-config
      - powershell
    state: present

- name: Install Webmin
  when:
    - ubtu22_pkg_webmin
  become: true
  ansible.builtin.apt:
    name:
      - webmin
    state: present

- name: Install hardware packages
  when:
    - not ubtu22_vm
  become: true
  ansible.builtin.apt:
    name:
      - lshw
      - hw-probe
    state: present

- name: Install SNMP
  when:
    - ubtu22_pkg_snmp
  become: true
  ansible.builtin.apt:
    name:
      - snmpd
      - snmp-mibs-downloader
    state: present
