    - name: Download the Microsoft repository key file
      get_url:
        url: "https://packages.microsoft.com/config/ubuntu/{{ ansible_lsb.release }}/packages-microsoft-prod.deb"
        dest: "/tmp/packages-microsoft-prod.deb"

    - name: Register the Microsoft repository key
      become: yes
      apt:
        deb: "/tmp/packages-microsoft-prod.deb"

    - name: Remove the Microsoft repository key file
      file:
        path: "/tmp/packages-microsoft-prod.deb"
        state: absent

    - name: Add Microsoft APT repository
      become: yes
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main"
        state: present

    - name: Ensure all packages are up to date
      become: yes
      apt:
        update_cache: yes
        upgrade: full

    - name: Install required packages
      become: yes
      apt:
        name:
          - ufw
          - ethtool
          - htop
          - lshw
          - screen
          - nano
          - net-tools
          - dnsutils
          - openssl
          - build-essential
          - p7zip-full
          - hw-probe
          - snmpd
          - snmp-mibs-downloader
          - curl
          - gnupg
          - apt-transport-https
          - ca-certificates
          - libssl-dev
          - software-properties-common
          - openssh-server
          - uidmap
          - dbus-user-session
          - unattended-upgrades
          - pkg-config
        state: present

    - name: Install PowerShell Core
      become: yes
      apt:
        name: powershell
        state: present

    - name: Configure Webmin repository and install Webmin
      become: yes
      shell: |
        curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
        sh setup-repos.sh -f
        apt-get update
        apt-get install -y webmin --install-recommends
