name: Ansible

on: 
  push:
    branches-ignore:
      - master
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      # Cache pip packages and Python environment
      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/pip
            ~/.venv # if you use a virtual environment
          key: ${{ runner.os }}-pip-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-python-${{ matrix.python-version }}-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --cache-dir ~/.cache/pip ansible ansible-lint

      # Save the cache after dependencies are installed
      - name: Save pip and Python environment
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}

      - name: Run ansible-lint
        run: |
          ansible-lint --exclude .github proxmox -q -f sarif --sarif-file results.sarif | tee results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
