name: Ansible

on: 
  push:
    paths:
      - '**.yml'
    branches-ignore:
      - master
  pull_request:
    types: [opened, reopened]
    paths:
      - '**.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      lint_success: ${{ steps.lint_check.outputs.lint_success }}
      python-version: ${{ matrix.python-version }}
    permissions:
      security-events: write
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        shell: bash
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
     
      - name: Get Ansible dir
        id: ansible-dir
        shell: bash
        run: |
          echo "ansibledir=$(ansible-config dump | grep -Po '(?<=ANSIBLE_HOME\(default\) = )(.*)')" >> $GITHUB_OUTPUT

      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pip-cache.outputs.dir }}
            ${{ steps.ansible-dir.outputs.ansibledir }}
            
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('.github/workflows/ansible.yml') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade --cache-dir ~/.cache/pip pip ansible ansible-lint

      # Save the cache after dependencies are installed
      - name: Save pip and Python environment
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ steps.ansible-dir.outputs.ansibledir }}
            ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('.github/workflows/ansible.yml') }}

      - name: Run Ansible-lint
        id: lint_check
        continue-on-error: true
        run: |
          ansible-lint --exclude .github proxmox -f sarif > results.sarif
          echo "lint_success=$([[ $? -eq 0 ]] && echo true || echo false)" >> $GITHUB_ENV

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  playbook:
    needs: lint
    if: ${{ needs.lint.outputs.lint_success == 'true' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.lint.outputs.python-version }}

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory site.yml
